http:
  routers:
    traefik:
      rule: 'Host(`monitor.docker.localhost`)'
      service: 'api@internal'
      entryPoints:
        - 'https'
        - 'http'
      tls:
        domains:
          - main: 'docker.localhost'
            sans:
              - '*.docker.localhost'

tls:
  certificates:
    - certFile: '/etc/certs/cert.pem'
      keyFile: '/etc/certs/key.pem'
